# Generated by Django 4.2.3 on 2023-10-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_user_products_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
