# Generated by Django 4.2.3 on 2023-10-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
