# Generated by Django 4.2.3 on 2023-11-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_product_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_discounted_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_original_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
