# Generated by Django 4.2.3 on 2023-11-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_product_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
