# Generated by Django 4.2.3 on 2023-11-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='size',
        ),
        migrations.AddField(
            model_name='mobile',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
